[package]
name = "themer-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.9"
config = "0.14.0"
env_logger = "0.11.3"
hyprland = "0.4.0-alpha.2"
log = "0.4.22"
serde = "1.0.204"
sysinfo = "0.30.13"
