[General]
colorscheme = "default"

[Hyprland]
enable = false
transparency = 1.0
rounding = 0
opacity = 1

[Hyprland.blur]
enable = false
size = 0
passes = 0

[Kitty]
enable = false
path = "~/.config/kitty/test.conf"

[Swww]
enable = false
wallpaper_dir = "~/Pictures/Wallpaper/"
wallpaper = "wallpaper.png"

[Tmux]
enable = false
path = "~/.config/tmux/test.conf"
