[General]
colorscheme = "default"

[Hyprland]
enable = false
transparency = 1.0
rounding = 0
opacity = 1

[Hyprland.blur]
enable = false
size = 0
passes = 0

[Kitty]
enabled = false
path = "~/.config/kitty/test.conf"
